# Generated by Django 5.0 on 2024-01-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_url_quiz_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
