# Generated by Django 5.0 on 2024-01-04 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_choices_is_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='is_selected',
            new_name='select',
        ),
    ]
