# Generated by Django 5.0 on 2024-01-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_rename_is_selected_choices_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='select',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
