# Generated by Django 5.0 on 2024-01-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_choices_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='select',
            field=models.BooleanField(default=False),
        ),
    ]
